version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: voterly
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./mysql/master/my.cnf:/etc/mysql/conf.d/replication.cnf
    networks:
      - mysql-network
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --binlog-do-db=voterly

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: voterly
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - mysql-slave-data:/var/lib/mysql
      - ./mysql/slave/my.cnf:/etc/mysql/conf.d/replication.cnf
    networks:
      - mysql-network
    depends_on:
      - mysql-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=ROW --binlog-do-db=voterly --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-master-data:
  mysql-slave-data:
